name: Build Pythia
on: [push]
jobs:
  Build-DLL:
    runs-on: windows-2019
    strategy:
      matrix:
        arch: [x64, x86]

    steps:
      - name: Setup Python 3.7 (${{ matrix.arch }})
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: ${{ matrix.arch }}
      - run: new-item -itemtype Junction -path c:\python37-x64 -target C:\hostedtoolcache\windows\Python\3.7.9\${{ matrix.arch }}
      - run: new-item -itemtype Junction -path c:\python37 -target C:\hostedtoolcache\windows\Python\3.7.9\${{ matrix.arch }}

      - name: Check out repository code
        uses: actions/checkout@v2

      # Build the extension
      - run: mkdir ninja_${{ matrix.arch }}
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - run: cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
        working-directory: ninja_${{ matrix.arch }}
      - run: ninja
        working-directory: ninja_${{ matrix.arch }}

      - uses: actions/upload-artifact@v2
        with:
          name: Pythia_DLLs
          path: |
            @Pythia/*.dll
            @Pythia/*.exe
          if-no-files-found: error

  Build-PBO:
    needs: Build-DLL
    runs-on: windows-2019
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Download the DLLs
        uses: actions/download-artifact@v2
        with:
          name: Pythia_DLLs
          path: "@Pythia"

      - run: dir "@Pythia"

      # Build PBOs and pack
      - name: Install Mikero's tools
        uses: arma-actions/mikero-tools@latest
      - run: pip install pefile
      - run: python tools\rebuild_all.py

      - uses: actions/upload-artifact@v2
        with:
          name: Pythia
          path: "@Pythia.zip"
          if-no-files-found: error
