name: Build Pythia
on: [push]
jobs:
  Build-PBOs:
    runs-on: windows-latest
    steps:
      - run: vswhere -nologo -products Microsoft.VisualStudio.Product.Community -property installationPath
      - run: vswhere -nologo -products * -property installationPath
      - name: Setup Python 3.7 (x86)
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x86'
      - name: Setup Python 3.7 (x64)
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - run: new-item -itemtype Junction -path c:\python37-x64 -target C:\hostedtoolcache\windows\Python\3.7.9\x64
      - run: new-item -itemtype Junction -path c:\python37 -target C:\hostedtoolcache\windows\Python\3.7.9\x86

      - name: Check out repository code
        uses: actions/checkout@v2

      # Build 64-bit extension
      - run: mkdir ninja_x64
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - run: cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
        working-directory: ninja_x64
      - run: ninja
        working-directory: ninja_x64

      # Build 32-bit extension
      - run: mkdir ninja_x86
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - run: cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
        working-directory: ninja_x86
      - run: ninja
        working-directory: ninja_x86

      # Build PBOs and pack
      - name: Install Mikero's tools
        uses: arma-actions/mikero-tools@latest
      - run: pip install pefile
      - run: python tools\rebuild_all.py

      - uses: actions/upload-artifact@v2
        with:
          name: Pythia
          path: "@Pythia.zip"
