name: Build Pythia
on: [push]
jobs:
  Build-PBOs:
    runs-on: windows-latest
    steps:
      - name: Setup Python 3.7 (x86)
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x86'
      - name: Setup Python 3.7 (x64)
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - run: new-item -itemtype Junction -path c:\python37-x64 -target C:\hostedtoolcache\windows\Python\3.7.9\x64
      - run: new-item -itemtype Junction -path c:\python37 -target C:\hostedtoolcache\windows\Python\3.7.9\x86

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3

      - uses: arma-actions/mikero-tools@latest

      - name: Check out repository code
        uses: actions/checkout@v2

      - run: |
          mkdir vcproj
          cd vcproj
          cmake .. -G "Visual Studio 16 2019" -A Win32
          cd ..
          mkdir vcproj64
          cd vcproj64
          cmake .. -G "Visual Studio 16 2019" -A x64
          cd ..

      - run: msbuild vcproj\PythiaProject.sln /m /p:Configuration=RelWithDebInfo /p:Platform=Win32
      - run: msbuild vcproj64\PythiaProject.sln /m /p:Configuration=RelWithDebInfo /p:Platform=x64

      - run: pip install pefile
      - run: python tools\rebuild_all.py

      - uses: actions/upload-artifact@v2
        with:
          name: Pythia
          path: "@Pythia.zip"
